dist: xenial
language: python
python:
  - "3.5"
git:
  depth: false
install:
  skip
script:
  skip
deploy:
  provider: pypi
  server: https://${PYPI_SERVER}
  distributions: "sdist bdist_wheel"
  username: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    tags: true

